# general
quit = q
undo = u
redo = U
search = /
help = ?
due = !

# navigation
previous = k
next = j
left = h
right = l
bottom = G
top = g

# new tasks
new = n
newAbove = O
newBelow = o
duplicate = p

# editing tasks
edit = a
clear = c
delete = d
detail = i
dueDate = @
clearDate = <Backspace>

# moving tasks
moveUp = K
moveDown = J
# move to top of previous list
moveLeftTop = H
# move to top of next list
moveRightTop = L
# move to bottom of previous list
moveLeftBottom = b
# move to bottom of next list
moveRightBottom = f
# move to bottom of last list
complete = <Space>
# select a list to move to
moveMenu = M

# lists
listNew = N
listEdit = C
listDelete = D
listRight = >
listLeft = <
