[default]

default.fg = brightBlue

[other]

; status bar
statusBar.bg = black
statusBar.fg = white

; list title
title.fg = brightMagenta
titleCurrent.fg = cyan

; current task
taskCurrent.fg = magenta

; subtasks
; selected
subtaskCurrent.fg = magenta
; incomplete
subtaskIncomplete.fg = brightBlue
; complete
subtaskComplete.fg = green

; disabled
disabled.fg = white
agenta

; subtasks
; selected
subtaskCurrent.fg = magenta
; incomplete
subtaskIncomplete.fg = brightBlue
; complete
subtaskComplete.fg = brightGreen

; disabled
disabled.fg = brightYellow
