local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

require('snacks').keymap.set("n", "<leader>hp", ui.toggle_quick_menu)
require('snacks').keymap.set("n", "<leader>ha", mark.add_file)
require('snacks').keymap.set("n", "<leader>h1", function() ui.nav_file(1) end)
require('snacks').keymap.set("n", "<leader>h2", function() ui.nav_file(2) end)
require('snacks').keymap.set("n", "<leader>h3", function() ui.nav_file(3) end)
require('snacks').keymap.set("n", "<leader>h4", function() ui.nav_file(4) end)
require('snacks').keymap.set("n", "<leader>h5", function() ui.nav_file(5) end)
