-- require('pretty-fold').setup(
--     {
--         sections = {
--             left = {
--                 'content',
--             },
--             right = {
--                 ' ', 'number_of_folded_lines', ': ', 'percentage', ' ',
--                 function(config) return config.fill_char:rep(3) end
--             }
--         },
--         fill_char = '•',
--
--         remove_fold_markers = false,
--         keep_indentation = true,
--         process_comment_signs = false,
--         comment_signs = {},
--
--         -- List of patterns that will be removed from content foldtext section.
--         stop_words = {
--             '@brief%s*', -- (for C++) Remove '@brief' and all spaces after.
--         },
--
--         add_close_pattern = true, -- true, 'last_line' or false
--
--         matchup_patterns = {
--             { '{',  '}' },
--             { '%(', ')' }, -- % to escape lua pattern char
--             { '%[', ']' }, -- % to escape lua pattern char
--         },
--
--         ft_ignore = { 'neorg' },
--     }
-- )
